# Generated by Django 4.1.1 on 2022-12-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercomment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
